// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnjwxpbwrttodbcufyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbmp3eHBid3J0dG9kYmN1ZnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTYzMzEsImV4cCI6MjA1NzAzMjMzMX0.aXZC9TP83fHbtGhJG4BWedP_E7gb_vN8hqEt0SYZ3EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);